name: Deploy AWS Lambda

on:
  push:
    branches:
      - main
    paths:
      - 'lambda/**'

jobs:
  deploy-lambda:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12' # Use a stable version

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r lambda/requirements.txt -t lambda_package/
    
    - name: Prepare Deployment Package
      run: |
        cd lambda
        rm -f lambda.zip  # Ensure no old zip files exist
        zip -r ../lambda.zip . ../lambda_package/
        cd ..

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Deploy Lambda Function
      run: |
        aws lambda update-function-code --function-name my-test-cicd-lambda --zip-file fileb://lambda.zip               